input/day%.txt:
	@scripts/fetch.sh $*

.SECONDEXPANSION:
processed/DayIn%.v: input/day%.txt $$(wildcard src/Day$$*.prep)
	@mkdir -p processed
	@echo -e "Require Export Day$*." > $@
	@echo -e "Definition inp := input" >> $@
	@if [ -f src/Day$*.prep ]; \
	  then src/Day$*.prep < input/day$*.txt ; \
	  else cat input/day$*.txt ; \
	fi >> $@
	@echo -e ".\nTime Compute main inp." >> $@
